In [2]:
def hour_min_sec(second):
    hour = second // 3600
    time_left = second % 3600
    
    minute = time_left // 60
    sec = time_left % 60
    
    return (hour, minute, sec)

hour, minute, sec = hour_min_sec(57894)
print("%d시간 %d분 %d초"%(hour,minute,sec))

16시간 4분 54초


In [25]:
def get_min_max(i) :
    minn = min(i)
    maxx = max(i)
    i.remove(minn)
    i.remove(maxx)
    
    return minn, maxx
    
l = [3,5,9,1,2]
(min_val, max_val) = get_min_max(l)

print(min_val)
print(max_val)
print(l)

1
9
[3, 5, 2]


In [188]:
def svd(v1, v2):
    #sumproduct = 0
    #for i in v1 :
    #    for j in v2 :
    #        if i == j :
    #            sumproduct += v1[i]*v2[j]
                
    return sum([v1[k]*v2[k] for k in v1 if k in v2])

In [211]:
def svd(v1, v2):
    res = 0
    
    for k in (set(v1) & set(v2)) :
        res += v1[k] * v2[k]
        
    return res

In [212]:
v1 = {'a':5}
v2 = {'a':3,'b':2}
svd(v1, v2)

15

In [213]:
v1 = {'c':5}
v2 = {'a':2,'b':1}
svd(v1, v2)

0

In [214]:
v1 = {'a':5,'b':4}
v2 = {'a':-1,'b':2}
svd(v1, v2)

3

In [201]:
import random

print("** 로또 추첨을 시작합니다. **")
print("추첨된 로또 번호 ==> ",*random.sample([i for i in range(1,46)],6), end=" ")  

** 로또 추첨을 시작합니다. **
추첨된 로또 번호 ==>  15 22 3 17 39 32 

In [318]:
import time

def letter_dict(strr):
    dictt = {}
    for i in set(strr) :
        dictt[i] = 0
        
    for i in strr :
        dictt[i] +=1
        
    return dictt
    
def max_letter(dictt) :
    maxx = max(dictt.items(), key=lambda item: item[1])
    return maxx[0]

In [368]:
a = letter_dict('red apple')
print(a)
print(max_letter(a))

{'a': 1, 'l': 1, 'd': 1, 'p': 2, 'e': 2, 'r': 1, ' ': 1}
p


In [369]:
def comb_dict(v1, v2):
    v3 = {}
    v4 = {}
    for k in (set(v1) & set(v2)) :
        v3[k] = (v1[k] + v2[k]) 
    
    v4 = v1.copy()
    v4.update(v2)
    v4.update(v3)
    
    return v4

In [370]:
b = letter_dict('yellow banana')
c = comb_dict(a,b)

print(c)
print(max_letter(c))

{'a': 4, 'l': 3, 'd': 1, 'p': 2, 'e': 3, 'r': 1, ' ': 2, 'w': 1, 'y': 1, 'b': 1, 'o': 1, 'n': 2}
a


In [371]:
a

{'a': 1, 'l': 1, 'd': 1, 'p': 2, 'e': 2, 'r': 1, ' ': 1}

In [372]:
b

{'a': 3, 'l': 2, 'w': 1, 'y': 1, 'b': 1, 'o': 1, 'e': 1, ' ': 1, 'n': 2}

# CLASS 함수

In [375]:
class Account :
    number = '0000-000-000000'
    balance = 0
    rate = 1.0
    
    def deposit (self, money):
        self.balance += money
    def withdraw (self, money):
        self.balance -= money
    def obtain_interest(self):
        self.balance += self.balance*(self.rate/100)

In [387]:
acc1 = Account()
acc2 = Account()
acc3 = Account()

acc1.deposit(500)
acc2.deposit(1000)

In [388]:
print(acc1.balance)
print(acc2.balance)
print(acc3.balance)

500
1000
0


In [389]:
acc2.obtain_interest()

In [390]:
print(acc2.balance)

1010.0


# 기본값 생성자

In [443]:
class Account :
    def __init__(self, num='000-000-00000', amnt=0, rate=3.0):
        self.number = num
        self.balance = amnt
        self.rate = rate
    
    def deposit (self, money):
        self.balance += money
    def withdraw (self, money):
        self.balance -= money
    def obtain_interest(self):
        self.balance += self.balance*(self.rate/100)

In [404]:
acc1 = Account()
acc2 = Account()
acc3 = Account()

print(acc1.balance)
print(acc2.balance)
print(acc3.balance)

0
0
0


In [128]:
class Account :
    num_acc = 0
    def __init__(self, num='000-000-00000', amnt=0, rate=3.0):
        self.number = num
        self.balance = amnt
        self.rate = rate
        Account.num_acc += 1
    
    def deposit (self, money):
        self.balance += money
    def withdraw (self, money):
        self.balance -= money
    def obtain_interest(self):
        self.balance += self.balance*(self.rate/100)
    def get_balance(self) :
        return self.balance
    def set_balance(self, amnt):
        self.balance = amnt
    
    def __add__(self, another) :
        new_acc = Account(amnt=self.balance+another.balance, rate=self.rate)
        return new_acc
    def __repr__(self):
        return str(self.balance)
    
    def transfer (self, another, amnt):
        if self.withdraw(amnt) :
            another.deposit(amnt)

In [129]:
acc1 = Account()
acc2 = Account()
acc3 = Account()

In [130]:
acc1.deposit(500)
acc2.deposit(1000)

In [131]:
print(acc1.num_acc)
print(Account.num_acc)

3
3


In [132]:
class MinBalanceAcc(Account) :
    def __init__(self, min_balance, num='000-000-00000', amnt=0, rate=1.0):
        Account.__init__(self, num=num, amnt=amnt,rate=rate)
        self.minimum_balance = min_balance
        self.bonus_rate = 1.0
    def withdraw (self, amnt):
        if self.balance - amnt < self.minimum_balance:
            print ('Sorry, Minimum balance must be maintained')
            return False
            
        else :
            Account.withdraw(self, amnt)
            return True
        
    def obtain_interest(self) :
        self.balance += (self.balance)*((self.rate+self.bonus_rate)/100.0)

# 5일차

In [133]:
acc3 = acc1+acc2

In [134]:
print(acc3.get_balance())

1500


In [135]:
acc1 = MinBalanceAcc(min_balance=0)
acc1.set_balance(500)
acc2 = MinBalanceAcc(min_balance=0)
acc2.set_balance(1000)

In [136]:
acc1.transfer(acc2, 100)
print(acc1.get_balance())
print(acc2.get_balance())

400
1100


In [137]:
acc1

400

# NUMPY

In [138]:
import numpy as np

In [146]:
a=np.array([1,2,3])
print(type(a))
print(a.shape)
print(a[0],a[1],a[2])
a[0] = 5
print(a)

b = np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(b[0,0],b[0,1],b[1,0])

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


In [148]:
a = np.zeros((2,2)) # 모든 값이 0인 2x2 array 생성
print(a)
b = np.ones((1,2)) # 모든 값이 1인 1x2 array 생성
print(b)
c = np.full((2,2), 7) # 모든 값이 7인 2x2 array 생성
print(c)
d = np.eye(2) # 2x2 단위행렬(Identity matrix) 생성
print(d)
e = np.random.random((2,2)) # 0~1 랜덤 값을 가지는 2x2 array 생성
print(e)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.9046418  0.44104336]
 [0.22270255 0.51477642]]


In [150]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
#-> 1부터 끝


#첫번째 행의 처음부터 2 앞까지(0,1), 두번째 행에서
#1부터 3 앞까지(1,2)의 값들을 떠와 b에 할당.
#따라서 b 는 다음과 같은 2x2 array:
#[[2 3]
#[6 7]]


b = a[:2, 1:3]
print(a[0, 1])
b[0, 0] = 77
print(a[0, 1])
# Slicing을 한다고 해서 값을 복사해가는 것이 아니므로
# 값의 변화가 동시에 일어남

2
77


In [151]:
# 2차원 배열(3x4) 생성
# [[ 1 2 3 4]
# [ 5 6 7 8]
# [ 9 10 11 12]]
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
# 두 번째 행의 값들을 모두 가져오는 두 가지 방법
row_r1 = a[1, :]
# 1차원 행렬 (4,)
row_r2 = a[1:2, :] # 2차원 행렬 (1x4) – 기존 차원 유지
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
# 두 번째 열의 값들을 모두 가져오는 두 가지 방법
col_r1 = a[:,1]
col_r2 = a[:,1:2]
print(col_r1,col_r1.shape)
print(col_r2,col_r2.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [156]:
# 2차원 배열(3x2) 생성
# [[ 1 2]
# [ 3 4]
# [ 5 6]]
a = np.array([[1, 2], [3, 4], [5, 6]])
# [1 4 5] 1차원 행렬(3,)을 얻는 두 가지 방법
print(a[[0, 1, 2], [0, 1, 0]])
print(a[range(3), [0, 1, 0]])
print(a[np.array(range(3)), [0, 1, 0]])
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))
# [2 2] 1차원 행렬(2,)을 얻는 두 가지 방법
print(a[[0, 0], [1, 1]])
print(np.array([a[0, 1], a[0, 1]]))

[1 4 5]
[1 4 5]
[1 4 5]
[1 4 5]
[2 2]
[2 2]


In [159]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a)

b = np.array([0, 2, 0, 1])
print(a[np.arange(4), b]) # [1 6 7 11]

a[np.arange(4), b] += 10

print(a) 
# array([[11, 2, 3],
#[ 4, 5, 16],
#[17, 8, 9],
#[10, 21, 12]])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [161]:
import numpy as np
x = np.array([1, 2])
print(x.dtype) # prints “int64”
x = np.array([1.0, 2.0])
print(x.dtype) # “float64”
x = np.array([1, 2], dtype=np.float64) # 데이터타입 명시
print(x.dtype) # “int64”

int64
float64
float64


In [162]:
import numpy as np
# Elementwise product
# [[ 5.0 12.0]
# [21.0 32.0]]
x = np.array([[1, 2], [3, 4]], dtype=np.float64)
y = np.array([[5, 6], [7, 8]], dtype=np.float64) 
print(x * y)
print(np.multiply(x, y))
# Elementwise sum
# [[ 6.0 8.0]
# [10.0 12.0]]


# Elementwise division
# [[0.2 0.33333333]
print(x + y) # 0.5
print(np.add(x, y)) print(x / y)
[0.42857143
]]
print(np.divide(x, y))
# Elementwise difference
# [[-4.0 -4.0] # Elementwise square root
# # [[1. 1.41421356]
print(x – y) # 2.
print(np.subtract(x, y)) print(np.sqrt(x))
[-4.0 -4.0]]
[1.73205081
]]

SyntaxError: invalid syntax (<ipython-input-162-668a908c326f>, line 5)

In [164]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])
# v · w = 219
print(v.dot(w))
print(np.dot(v, w))
# 매트릭스 / 벡터 곱; [29 67]
print(x.dot(v))
print(np.dot(x, v))
# 매트릭스 / 매트릭스 곱;
# [[19 22]
#[43 50]]
print(x.dot(y))
print(np.dot(x, y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [165]:
import numpy as np
x = np.array([[1, 2], [3, 4]])
print(np.sum(x))
# 모든 원소의 합
print(np.sum(x, axis=0)) # 각 열의 합
print(np.sum(x, axis=1)) # 각 행의 합

10
[4 6]
[3 7]


In [166]:
x = np.array([[1, 2], [3, 4]])
print(x)
print(x.T)
# 전치행렬 (Transposed mat.)
v = np.array([1,2,3])
print(v)
# prints “[1 2 3]”
print(v.T)
# prints “[1 2 3]”

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


In [168]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
v = np.array([1,0,1])
y = np.empty_like(x) # x와 같은 shape의 빈 매트릭스 만들기
# x의 각 행에 v와 elementwise 합을 하여 y의 해당 행에 할당
for i in range(4):
    y[i, :] = x[i, :] + v
# [[ 2 2 4]
# [[ 5 5 7]
# [[ 8 8 10]
# [ 11 11 13]]
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [171]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
v = np.array([1,0,1])
vv = np.tile(v, (4, 1)) # v 내용을 4x1의 각 행에 반복함
print(vv)
# [[ 2 2 4]
# [[ 5 5 7]
# [[ 8 8 10]
# [ 11 11 13]]
y = x + vv
print(y)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [172]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
v = np.array([1,0,1])
# 브로드캐스팅을 사용하여 x의 각 행에 v값을 더함
y = x + v
# [[ 2 2 4]
# [[ 5 5 7]
# [[ 8 8 10]
# [ 11 11 13]]
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [176]:
one = np.array([[1,1],[2,1]])
two = np.array([[15],[25]])
func = ([[a],[b]])

In [186]:
func = np.dot(np.linalg.inv(one), two)

In [187]:
print(func)

[[10.]
 [ 5.]]


In [188]:
func2 = np.linalg.inv(one) * two
print(func2)

[[-15.  15.]
 [ 50. -25.]]
